@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 30
skinparam maxmessagesize 90
skinparam sequenceParticipant underline

actor 商户 as S
participant "新建商品" as A
participant "选择类目" as B
participant "选择标签" as C
participant "创建商品" as D

S -> A: 填写基本信息
activate A

group 选择类目标签
        A -> B: 根据名称推荐类目
        activate B

        B -> C: 根据类目获取标签
        activate C
        C --> B: 根据标签key返回标签值
        activate B

end

S -> D: 创建商品
activate D

D --> S: 200
activate A


@enduml